{% set name = "python-pcl" %}
{% set version = "0.3.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strawlab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3871a8b77f389fbd1f99c5447e5174bf7bebc94e80cd7b2733ec15fc4fa55b10
  patches:
    - patches/0001-Mark-PCLBase-as-nogil-to-fix-compilation.patch
    - patches/0002-Enable-visualization-module.patch
    - patches/0003-Remove-ConditionalRemoval-API-and-add-deprecation-no.patch
    - patches/0003-Remove-ConditionalRemoval-API-and-add-deprecation-no-2.patch
    - patches/0004-Add-support-for-PCL-1.9.patch
    - patches/0005-add-support-for-pcl-1.10.patch
    - patches/0006-use-pcl-1.11-api.patch
    - patches/0006-use-pcl-1.11-api-2.patch
    - patches/0007-support-for-pcl-1.12.patch
    - patches/0008-fix-deprecated-collections-import-since-.patch
    - patches/0010-use-distutils-instead-of-setuptools-for-.patch
    - patches/0011-Support-PCL-1.13-and-later.patch
    - patches/0013-add-conda-prefix.patch
    - patches/0014-fix-numpy2.patch
    - patches/0015-support-win.patch


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 12

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkgconfig
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython 0.29                            # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - libboost-devel
    - pcl
    - vtk-base  # [win]
    - python
    - setuptools
    - numpy
    - cython 0.29
    - pip
    - flann
    - libcxx  # [osx]
  run:
    - python
    - cython
    - filelock
    - nose
    - pcl
    - flann

test:
  imports:
    - pcl
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/strawlab/python-pcl
  summary: Python bindings for the Point Cloud Library (PCL) using Cython.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
